### ISSUE TITLE
Improve Permission Handling UI

### ISSUE THREAD

**Issue by odaridavid** [odaridavid/WeatherApp#29]

**Comment by devedroy** [comment]
Hi @odaridavid  I would like to work on this issue.
Can you please assign this to me?
Thankyou.

**Comment by odaridavid** [comment]
Sure, go ahead

**Comment by devedroy** [comment]
I don't see any related code references linked to this issue, can you please guide on where to start from?

**Comment by odaridavid** [comment]
~~Hey, sorry missed this comment and was off this codebase for a while, it's the settings dialogs for the current options.~~

<img src="https://github.com/odaridavid/WeatherApp/assets/20339228/49ce2192-d5fc-4bc3-995c-26d91c37e35d" width="300"/>
